services:
  comandas.api:
    image: ${DOCKER_REGISTRY-}comandasapi
    build:
      context: .
      dockerfile: Comandas.Api/Dockerfile
    networks:
      - postgres-network
  
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: joao
      POSTGRES_DB: comandas_database
      POSTGRES_PASSWORD : password
    ports:
      - 15432:5432
    networks:
      - postgres-network
    volumes:
      - comandadb-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: joao@joao.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks: 
  postgres-network:
    driver: bridge  

volumes:
  comandadb-data:
  pgadmin-data:
    